# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjectTemplate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProjectTemplate
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SDWebImage', '~> 5.0'
  pod 'Log'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Alamofire'
  
  target 'ProjectTemplateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProjectTemplateUITests' do
    # Pods for testing
  end

end
